# Projeto: sophos_kodiak
# Descrição: A new Flutter project.
#
# -----------------------------
# Dependências principais
# -----------------------------
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.3.2
  fl_chart: ^1.0.0
  logger: ^2.4.0

# -----------------------------
# Dependências de desenvolvimento
# -----------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  http_mock_adapter: ^0.6.1

# -----------------------------
# Configurações do Flutter
# -----------------------------
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: AntonSC
      fonts:
        - asset: assets/fonts/AntonSC-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf

# -----------------------------
# Ambiente
# -----------------------------
environment:
  sdk: ^3.8.0

# -----------------------------
# Outras informações
# -----------------------------
name: sophos_kodiak
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
